---
-
  become: true
  hosts: cms

  #roles:
    #- role: "nickjj.docker"
      #tags: ["docker"]

  tasks:
    -
      name: install deps
      apt:
        update-cache: yes
        name:
          - build-essential
          - openjdk-8-jdk-headless
          - fp-compiler
          - postgresql
          - postgresql-client
          - python3.6
          - python-docker
          - cppreference-doc-en-html
          - cgroup-lite
          - libcap-dev
          - zip

    - name: prep cms dir
      file:
        path: /data/cms
        state: directory
        recurse: yes
    -
      name: clear cms network
      docker_network:
        name: cms
        state: absent

    -
      name: cms network
      docker_network:
        name: cms

    -
      name: create cms config
      template:
        src: "templates/cms.conf.j2"
        dest: "/data/cms/cms.conf"

    #-
      #name: copy contest
      #copy:
        #src: "files/contest"
        #dest: "/data/cms/contest/"
      #synchronize:
        #src: "files/contest"
        #dest: "/data/cms/contest/"
        #archive: "no"
        #recursive: "yes"
        #delete: "yes"

    -
      name: cms database
      docker_container:
        name: cmsdb
        image: postgres:9.4
        env:
          POSTGRES_USER: cmsuser
          POSTGRES_DB: cmsdb
          POSTGRES_PASSWORD: cms
        purge_networks: yes
        networks:
          - name: cms
            aliases:
            - cmsdb
      
    -
      name: cms logger
      docker_container:
        name: cmslog
        image: mloc6/cms
        entrypoint: cmsLogService
        volumes:
          - "/data/cms/cms.conf:/usr/local/etc/cms.conf:ro"
        recreate: yes
        networks:
          - name: cms
            aliases:
            - cmslog

    -
      name: cms server
      docker_container:
        name: cms
        image: mloc6/cms
        privileged: yes
        volumes:
          - "/data/cms/cms.conf:/usr/local/etc/cms.conf:ro"
          - "/data/cms/contest:/contest"
          - "/data/cms/run:/data"
        recreate: yes
        networks:
          - name: cms
            aliases:
            - cms
        ports:
          - "8888:8888"
          - "8889:8889"
